blank_issues_enabled: true

contact_links:
- name: 🛡 License issues
  url: https://kanmail.io/support
  about: Purchase and recover Kanmail licenses.

- name: 📖 Documentation
  url: https://kanmail.io/docs
  about: View the Kanmail user documentation.
