name: "Build Kanmail"

on:
  push:
    branches:
      - windows-github-builds

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Windows
            runs-on: windows-2016
            requirements-file: windows.txt

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # JavaScript client build
      - name: Install yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16.1.0

      - name: Install yarn packages
        run: yarn install --frozen-lockfile

      - name: Build JS bundle
        run: yarn build

      # Python app build
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Sync pip packages
        run: pip-sync requirements/${{ matrix.requirements-file }}

      - name: Make empty .pyupdater directory
        run: mkdir .pyupdater

      - name: Copy in fake config file
        run: cp make/github-config.pyu .pyupdater/config.pyu

      - name: Build
        run: python -m make
        env:
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}

      - name: Install AWS CLI
        run: pip install awscli

      - name: Upload to S3
        run: aws s3 sync pyu-data/new/ s3://builds.kanmail.io/
        env:
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
