name: "Build Kanmail"

on:
  push:
    tags:
    branches:
      - main

jobs:
  build:
    # Build platforms definition
    strategy:
      matrix:
        include:
          - name: Windows
            runs-on: windows-2016
            requirements-file: windows.txt

          - name: macOS
            runs-on: macos-10.15
            requirements-file: macos.txt

          - name: Linux
            runs-on: ubuntu-18.04
            requirements-file: linux.txt

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}

    env:
      MACOSX_DEPLOYMENT_TARGET: "10.9"

    steps:
      - name: Install apt packages
        if: ${{ matrix.name == 'Linux' }}
        run: sudo apt update && sudo apt install libcairo2-dev libgirepository1.0-dev libgtk-3-dev libwebkit2gtk-4.0-37 gir1.2-webkit2-4.0

      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f  # v2.3.4
        with:
          fetch-depth: 0  # ensure we fetch tags

      # JavaScript client build
      - name: Install yarn
        uses: actions/setup-node@aa759c6c94d3800c55b8601f21ba4b2371704cb7  # 2.3.0
        with:
          node-version: 16.1.0

      - name: Install yarn packages
        run: yarn install --frozen-lockfile

      - name: Build JS bundle
        run: yarn build

      # Python app build
      - name: Install Python (Windows, Linux)
        if: ${{ matrix.name != 'macOS' }}
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6  # v2.2.2
        with:
          python-version: 3.8.10

      # See: https://github.com/actions/virtual-environments/issues/1256#issuecomment-770270252
      - name: Install macOS Python pkg
        if: ${{ matrix.name == 'macOS' }}
        run: |
          curl https://www.python.org/ftp/python/3.8.10/python-3.8.10-macosx10.9.pkg -o "python.pkg"
          sudo installer -pkg python.pkg -target /
          echo "/Library/Frameworks/Python.framework/Versions/3.8/bin/" >> $GITHUB_PATH

      - name: Install pip packages
        run: pip3 install -r requirements/${{ matrix.requirements-file }}

      - name: Make empty .pyupdater directory
        run: mkdir .pyupdater

      - name: Copy in fake config file
        run: cp make/github-config.pyu .pyupdater/config.pyu

      - name: Make build
        run: python3 -m make
        env:
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}

      # Upload app to S3
      - name: Install AWS CLI
        run: pip3 install awscli

      - name: Upload to S3
        run: aws s3 sync --no-progress pyu-data/new/ s3://builds.kanmail.io/
        env:
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
