name: 'Mark & close stale/unassigned bug issues'
on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-close: 7
        days-before-stale: 30
        only-issue-labels: bug
        exempt-all-assignees: true
        stale-issue-message: 'This bug is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
